# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

# How many times to allow for planning retries before executing recovery behaviors. Default: -1.0 (infinite retries)
max_planning_retries: 0
recovery_behavior_enabled: false

# controller_frequency defines how frequently the local plan is updated
controller_frequency: 5.0
controller_patience: 3.0

# planner_frequency defines how frequently the global plan is calculated
planner_frequency: 0.0 
planner_patience: 5.0

oscillation_timeout: 0.0 # A value of 0.0 corresponds to an infinite timeout: no timer counting up to execute recovery behaviors
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner
